version: "3"
services:
  rsrdbhost:
    image: postgres:9.6.1
    restart: always
    environment:
    - POSTGRES_PASSWORD=mysecretpassword
    ports:
    - "5432:5432"
    volumes:
    - ./postgres:/docker-entrypoint-initdb.d/
  perms:
    build:
      context: .
      dockerfile: Dockerfile-dev
    network_mode: container:akvo_flow_together
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
networks:
  default:
    external:
      name: akvoflow_together